### PR TITLE
Updated to support Ghost 1.0.0

### PR DESCRIPTION
**Pull request by mmornati**
* Plugin updated and tested with Ghost 1.0.0
* Code is updated following the new Storage specifications

### CODE REVIEW

**Comment by mmornati** [comment]
@aphe can you please take care to the 'package.json' with your information into the contributors part? (you can make a pull request on my github repo with a pull request to this one... so it will be integrated automatically. I'm not sure it will be merged here cause I think @sethbrasile is not active anymore. But nevermind.

**Comment by mmornati** [comment]
Hey @sethbrasile... is there any chance to have all this PR accepted to push all the changes to the official NPM? I think it will get a better visibility for the plugin... especially because is the one referenced on the Ghost website and because the version 1.0.X is now official and it should be great to have it updated to the latest standards.
Let us know... I'm available to manage the repo if you don't have time to do it.

**Comment by morgs32** [comment]
@sethbrasile be a pal?

**Comment by mmornati** [comment]
Hey... Are you still alive? 
Any news on this repo? 
Can you accept this merge request to be compliant with the Ghost 1.X.X?

**Comment by sethbrasile** [comment]
So sorry folks! I sadly have not been on github in a while so I didn't know I had notifications. @mmornati, thank you for emailing me! I'd appreciate the help @mmornati, I'll add you as a maintainer.

**Comment by sethbrasile** [comment]
@mmornati I have also added you as a collaborator on NPM. Please let me know if you would like to help with anything else!

**Comment by mmornati** [comment]
Yeah you are still alive :) It is a pleasure to have you back.

Thanks for your actions. I will merge the latest version I've on the master
on my repo here on yours.
Then I will check with Ghost to know about the link on the Ghost page
(cause right now I saw they changed it to link to my repo).

I keep you informed and when you will be back on github (in 6 months or so
:P), we can check it together.

**Pull request merged**
