### PR TITLE
Updated the store plugin to respect Ghost 0.10.0 requirements

### PR DESCRIPTION
**Pull request by mmornati**

### CODE REVIEW

**Comment by mmornati** [comment]
Sorry about the multiple commits (I try to rebase and squash them but it wasn't working correctly). I was testing in my Docker and I needed to push on the repo to allow a new build.
I tested it and it is working correctly... at least on the upload image part. 

The new **required** methods: exists, delete are implemented following the Cloudinary NodeJS documentation, but I'm not sure when they are called (to be able to test them out).

I will go ahead checking this part and I'll submit any fix if needed.

**Comment by sethbrasile** [comment]
Apparently I wasn't "watching" this repo... so I missed this. I'll take a look! Thank you!

**Comment by carloscuesta** [comment]
Hello @sethbrasile @mmornati, Anything I can do ? Do you need help? Ghost is now at 0.11.1 and planing to launch a 1.x.x release.

Would be great to merge those changes 😃

**Comment by mmornati** [comment]
It is already good for 0.11. I'm using it on my blog and I'm on the latest
version. Not tested yet on version 1 but, as I'm using a Docker, I think I
can make a test quickly to be sure if it is ok.

**Comment by sethbrasile** [comment]
I'm so sorry guys! I took a new "9-5" and have been very busy!

If a few people wanted to give this PR a solid review and let me know that these changes are good, it will speed things along.

Any word on compatibility with 1.0 @mmornati ?

**Comment by carloscuesta** [comment]
The only thing I noticed @sethbrasile related to the @mmornati PR is the `baseStore require path`

This PR, in my use case doesn't works  and it's because the `baseStore require`. I've forked it and changed `baseStore` to use the Ghost node_module, instead of looking into `./../..` subdirectories, and worked.

``` diff
- baseStore = require('../../../core/server/storage/base');
+ baseStore = require('ghost/core/server/storage/base');
```

See [this commit](https://github.com/carloscuesta/ghost-cloudinary-store/commit/ea04820b17e9e9de44af09bfb8d1c1452e33cf4f)

**Comment by mmornati** [comment]
Not tested yet on 1.0. I'll give it a try in the next two days.

I'm OK about the changes proposed in the code review... It is really really
better :)  Thanks.

**Comment by mmornati** [comment]
Just tested the plugin on Ghost 1.0 Alpha 5. 
**It is working well without any change.**

schermata 2016-10-19 alle 22 07 59

schermata 2016-10-19 alle 22 08 29

I think it will be better to add error management into the save function: in case of errors uploading to cloudinary (wrong api key for example), an "unexisting" image is linked to the page but there is no feedback saying that the image was not uploaded.
It should be managed better though.

**Review by ertrzyiks — APPROVED** [review]
It works for me! I needed a fix from @carloscuesta, because I use ghost as a module

**Comment by carloscuesta** [comment]
In the meantime, you can use https://github.com/carloscuesta/ghost-cloudinary-store this directly from GitHub @ertrzyiks. Is what i'm doing now, as long this module gets updated :+1:

**Comment by sethbrasile** [comment]
@carloscuesta would you be interested in helping maintain this repo? I don't have the time but I would love to keep it maintained.

**Comment by sethbrasile** [comment]
Or @mmornati the offer extends to you as well. I'm sorry that I haven't kept up.

If neither of you are interested, @mmornati if you could make the change that @carloscuesta suggested, I'd be glad to merge and draft a new release.

The long pauses in my communication are because I don't end up on github much these days and don't see the notifications, so feel free to email me.

**Comment by mmornati** [comment]
No problem for me. About the @carloscuesta change, I think we can just push a pull request. What do you think about it @carloscuesta?

**Comment by carloscuesta** [comment]
Yes, we can push a fix to release a new version 👍 @mmornati. No problem on helping to maintain this repo, anyone in this PR could help too @sethbrasile 🎉

**Pull request merged**
