### PR TITLE
Add Cloudinary Image transformations API

### PR DESCRIPTION
**Pull request by aphe**

### CODE REVIEW

**Comment by mmornati** [comment]
Hey @aphe. Good Job and it is a thing I would like to use too.
Can I integrate your merge request and mine one too (the one for Ghost 1.0.0)?
I will rework it to fit in the new code format (I let you check it out if you want).
Thanks.

**Comment by aphe** [comment]
Yes, please.

**Comment by mmornati** [comment]
Wow... what a quick response :) I'll work on it today..... it should be easy.
Than I will check even about the size of the image 'cause it is not working so good with the new Casper theme: the same image is used both for small and large display (on the homepage and post page).

**Comment by mmornati** [comment]
Can you show me one cloudinary url uploaded using this version of the plugin?

**Comment by aphe** [comment]
https://res.cloudinary.com/tendabiru/image/upload/q_auto:good/anzjdnku8oil5gsawfzs.png
```
                configuration: {
                    quality: "auto:good",
                    secure: true
                }
```

this version can use all the API [here](http://cloudinary.com/documentation/image_transformations)

**Comment by mmornati** [comment]
And what about this code, into the _exists_ method:
`if (cloudinary.image(filename, { quality: 50 })) {`
Are you checking the existence of the file with a predefined quality?

**Comment by aphe** [comment]
@mmornati i guess that line can safely remove since ghost never really execute it?

i think that code accidentally get into commit, sorry.

**Comment by mmornati** [comment]
All is merged on the other side. I just tested locally on Ghost 1.0.2 and it is working very good. Great Job Man!! THANKS!
Don't know how you are using your ghost, but the latest version of the Docker I'm using is available with your contribution too.
I will put it on my blog later tomorrow...

**Comment by mmornati** [comment]
Already integrated taking changes from PullRequest made on mmornati/ghost-cloudinary-store repository.

**Pull request closed without merging**
